export default {
    techStack:[
        {
            name:'ts',
            title:'TS',
            description:'Typed JavaScript for stronger code.',
            link:'https://www.typescriptlang.org/',
        },
        {
            name:'react',
            title:'React',
            description:'JS library for building user interfaces.',
            link:'https://react.dev/',
        },
        {
            name:'mongodb',
            title:'MongoDB',
            description:'Scalable NoSQL database for flexible data storage.',
            link:'https://www.mongodb.com/',
        },
        {
            name:'css',
            title:'CSS',
            description:'Styling language for HTML documents.',
            link:'https://developer.mozilla.org/en-US/docs/Web/CSS',
        },
        {
            name:'js',
            title:'JS',
            description:'Dynamic scripting language for web development.',
            link:'https://developer.mozilla.org/en-US/docs/Web/JavaScript',
        },
        {
            name:'next',
            title:'Next.js',
            description:'React framework for server-side rendering.',
            link:'https://nextjs.org/',
        },
        {
            name:'sass',
            title:'SASS',
            description:'Advanced CSS preprocessor for efficient styling.',
            link:'https://sass-lang.com/',
        },
        {
            name:'redux',
            title:'Redux',
            description:'Predictable state management library for JavaScript apps',
            link:'https://redux.js.org/',
        },
        {
            name:'nextAuth',
            title:'Next Auth',
            description:'Next.js auth library with provider integration.',
            link:'https://next-auth.js.org/',
        },
        {
            name:'reactRouter',
            title:'React Router',
            description:'Routing library for declarative routing in React apps.',
            link:'https://reactrouter.com/en/main',
        },
        {
            name:'html',
            title:'HTML',
            description:'Standard language for web content structure and display.',
            link:'https://developer.mozilla.org/en-US/docs/Web/HTML',
        },
        {
            name:'tailwind',
            title:'Tailwindcss',
            description:'Highly customizable utility-first CSS framework.',
            link:'https://tailwindcss.com/',
        },
    ],
    projects:[
        {
            id:0,
            backgroundColor:"#D87D4A",
            frontgroundColor:"#191919",
            title:"audiophile",
            description:"Introducing my first React project, a sleek and modern e-commerce website designed for audiophiles. With a user-friendly interface, smooth navigation, and high-quality product images, this website creates an immersive shopping experience.",
            mobile:"/projects/audiophile/mobile.png",
            tablet:"/projects/audiophile/tablet.png",
            laptop:"/projects/audiophile/pc.png",
            live:"https://taha-khoumani.github.io/audiophile/",
            github:"https://github.com/taha-khoumani/audiophile",
            techStack:[
                "html",
                'js',
                'react',
                "sass",
                'redux',
                'reactRouter'
            ],
        },
        {
            id:1,
            backgroundColor:"linear-gradient(160.97deg, #56B7F3 0%, #A838EF 55.73%, #EA888A 100%)",
            frontgroundColor:"#384068",
            title:"Feedback App",
            description:"A full-stack web application designed to give users a seamless way to provide feedback on audiophile. Powered by MongoDB, the database allows for efficient and secure storage of user data. The app also utilizes NextAuth for authentication and login functionality.",
            mobile:"/projects/feedback/mobile.png",
            tablet:"/projects/feedback/tablet.png",
            laptop:"/projects/feedback/pc.png",
            live:"https://feedback-app-taha-khoumani.vercel.app/",
            github:"https://github.com/taha-khoumani/feedbackApp",
            techStack:[
                'next',
                'mongodb',
                'nextAuth',
                'react',
                "sass",
                'redux',
                'js',
                "html",
            ],
        },
        {
            id:2,
            backgroundColor:"#7C5DFA",
            frontgroundColor:"#373B53",
            title:"Invoice  App ",
            description:'A cutting-edge invoicing web application built with modern technology. This full-stack app was developed with TypeScript, providing a more efficient and error-free codebase. Authentication and login functionality are powered by Google, making it secure and easy to use.',
            mobile:"/projects/invoice/mobile.png",
            tablet:"/projects/invoice/tablet.png",
            laptop:"/projects/invoice/pc.png",
            live:"https://invoice-app-taha-khoumani.vercel.app/",
            github:"https://github.com/taha-khoumani/invoice_app",
            techStack:[
                'ts',
                'nextAuth',
                'mongodb',
                'next',
                'react',
                "sass",
                'redux',
                "html",
            ],
        },
    ],
}